micronaut:
  application:
    name: mymicroapp
  server:
    port: 8081
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
      - access: isAnonymous()
        pattern: /mymicroapp/**
      - access: isAnonymous()
        pattern: /clients/**
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    dialect: H2
hazelcast.network.addresses: '[''121.0.0.1:5701'']'
otel:
  traces:
    exporter: jaeger
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    entity-scan:
      packages: com.empreendapp.model
netty:
  default:
    allocator:
      max-order: 3


